import 'package:littlefish_core/terminal_management/models/terminal.dart';

// TODO: No need for this extension if we put this code inside of the Terminal file within littlefish_core

extension TerminalExtension on Terminal {
  Terminal copyWith({
    String? id,
    String? deviceId,
    String? name,
    String? displayName,
    String? description,
    DeviceInfo? device,
    AppInfo? app,
    String? userId,
    String? businessId,
    String? merchantId,
    String? providerId,
    bool? cardEnabled,
    String? status,
    String? serialNumber,
    String? terminalId,
    String? family,
    String? platform,
    String? product,
    String? type,
    String? version,
    String? board,
    String? bootLoader,
    String? brand,
    bool? isPhysicalDevice,
    DeviceType? deviceType,
    String? display,
    String? fingerprint,
    String? hardware,
    String? host,
    String? model,
    DateTime? dateCreated,
    DateTime? dateUpdated,
    bool? deleted,
    String? createdBy,
    String? updatedBy,
  }) {
    return Terminal(
      id: id ?? this.id,
      deviceId: deviceId ?? this.deviceId,
      name: name ?? this.name,
      displayName: displayName ?? this.displayName,
      description: description ?? this.description,
      device: device ?? this.device,
      app: app ?? this.app,
      userId: userId ?? this.userId,
      businessId: businessId ?? this.businessId,
      merchantId: merchantId ?? this.merchantId,
      providerId: providerId ?? this.providerId,
      cardEnabled: cardEnabled ?? this.cardEnabled,
      status: status ?? this.status,
      serialNumber: serialNumber ?? this.serialNumber,
      terminalId: terminalId ?? this.terminalId,
      family: family ?? this.family,
      platform: platform ?? this.platform,
      product: product ?? this.product,
      type: type ?? this.type,
      version: version ?? this.version,
      board: board ?? this.board,
      bootLoader: bootLoader ?? this.bootLoader,
      brand: brand ?? this.brand,
      isPhysicalDevice: isPhysicalDevice ?? this.isPhysicalDevice,
      deviceType: deviceType ?? this.deviceType,
      display: display ?? this.display,
      fingerprint: fingerprint ?? this.fingerprint,
      hardware: hardware ?? this.hardware,
      host: host ?? this.host,
      model: model ?? this.model,
      dateCreated: dateCreated ?? this.dateCreated,
      dateUpdated: dateUpdated ?? this.dateUpdated,
      deleted: deleted ?? this.deleted,
      createdBy: createdBy ?? this.createdBy,
      updatedBy: updatedBy ?? this.updatedBy,
    );
  }
}
