// File generated by FlutterFire CLI.

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRI3xRUjscfoyPD1Ps29qu4Fp6rIj_-MA',
    appId: '1:1090801020318:android:6046030f8414fae2f9ba8f',
    messagingSenderId: '1090801020318',
    projectId: 'littlefish-merchant-prod',
    databaseURL: 'https://littlefish-merchant-prod.firebaseio.com',
    storageBucket: 'littlefish-merchant-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCWq0n-s7cV_9A91v-RD-2Y7UYuJ9pruI',
    appId: '1:1090801020318:ios:6af634b379d19f1df9ba8f',
    messagingSenderId: '1090801020318',
    projectId: 'littlefish-merchant-prod',
    databaseURL: 'https://littlefish-merchant-prod.firebaseio.com',
    storageBucket: 'littlefish-merchant-prod.appspot.com',
    androidClientId:
        '1090801020318-17sp4teab8cem085v1pu4lakomp8p61c.apps.googleusercontent.com',
    iosClientId:
        '1090801020318-j05p6mt2n0csf6ul5cltc930m404vubq.apps.googleusercontent.com',
    iosBundleId: 'africa.nybble.littlefish-merchant',
  );
}
