// File generated by FlutterFire CLI.

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_local.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPHQFdCHYHLG2AmH3K-KOdLGAFZqgYjwA',
    appId: '1:394785306590:android:b1e3246701dea72d638f4f',
    messagingSenderId: '394785306590',
    projectId: 'littlefish-merchant-dev',
    databaseURL: 'https://littlefish-merchant-dev.firebaseio.com',
    storageBucket: 'littlefish-merchant-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq2mQ1iks3bHh0BZQqGsxClqJ1Pxa4-G4',
    appId: '1:394785306590:ios:a57d4d57a47c88ab638f4f',
    messagingSenderId: '394785306590',
    projectId: 'littlefish-merchant-dev',
    databaseURL: 'https://littlefish-merchant-dev.firebaseio.com',
    storageBucket: 'littlefish-merchant-dev.appspot.com',
    androidClientId:
        '394785306590-07o9o91jdeh03o0et9k17h8t7lf28g3n.apps.googleusercontent.com',
    iosClientId:
        '394785306590-bd97t7dhcda79h5krgqvs5ao18fq95mo.apps.googleusercontent.com',
    iosBundleId: 'africa.nybble.littlefish-merchant.local',
  );
}
