// ignore_for_file: prefer_single_quotes

const absaDefaultDesignSystem = {
  "primitive": {
    "brandPrimitive": {
      "brand1": {"name": "passion", "value": "0xFFDC0037"},
      "brand2": {"name": "power", "value": "0xFFB50232"},
      "brand3": {"name": "hope", "value": "0xFF95052A"},
      "brand4": {"name": "inspire", "value": "0xFF77021E"},
      "brand5": {"name": "energy", "value": "0xFFFF780F"},
      "brand6": {"name": "uplift", "value": "0xFFF93F24"},
      "brand7": {"name": "yellow80", "value": "0xFFFFB848"},
      "brand8": {"name": "undefined", "value": "0xFFFFFFFF"},
      "brand9": {"name": "undefined", "value": "0xFFFFFFFF"},
    },
    "statusPrimitive": {
      "status1": {"name": "error-text", "value": "0xFF910826"},
      "status2": {"name": "error-accent", "value": "0xFFC5163C"},
      "status3": {"name": "error-surface", "value": "0xFFFAD9E0"},
      "status4": {"name": "positive-text", "value": "0xFF168335"},
      "status5": {"name": "positive-accent", "value": "0xFF1CA643"},
      "status6": {"name": "positive-surface", "value": "0xFFF3FCE9"},
      "status7": {"name": "info-text", "value": "0xFF1F4D7A"},
      "status8": {"name": "info-accent", "value": "0xFF2B82DA"},
      "status9": {"name": "info-surface", "value": "0xFFEDF5F"},
      "status10": {"name": "warning-text", "value": "0xFF87310F"},
      "status11": {"name": "warning-accent", "value": "0xFFE35716"},
      "status12": {"name": "warning-surface", "value": "0xFFFDECE4"},
    },
    "neutralPrimitive": {
      "neutral1": {"name": "serene", "value": "0xFFFEFFFF"},
      "neutral2": {"name": "grey-04", "value": "0xFFF8F6F6"},
      "neutral3": {"name": "grey-08", "value": "0xFFECE9E9"},
      "neutral4": {"name": "grey-24", "value": "0xFFC7C5C5"},
      "neutral5": {"name": "grey-40", "value": "0xFFA19F9F"},
      "neutral6": {"name": "grey-60", "value": "0xFF686666"},
      "neutral7": {"name": "grey-72", "value": "0xFF4C4949"},
      "neutral8": {"name": "enrich", "value": "0xFF131010"},
    },
  },
  "semantic": {
    "brand": {
      "primary": "@primitive/brandPrimitive/brand3",
      "emphasized": "@primitive/brandPrimitive/brand4",
      "deEmphasized1": "@primitive/neutralPrimitive/neutral2",
      "deEmphasized2": "@primitive/neutralPrimitive/neutral3",
      "deEmphasized3": "@primitive/neutralPrimitive/neutral4",
    },
    "neutral": {
      "primary": "@primitive/neutralPrimitive/neutral7",
      "primaryInverse": "@primitive/neutralPrimitive/neutral1",
      "secondary": "@primitive/neutralPrimitive/neutral6",
      "emphasized": "@primitive/neutralPrimitive/neutral8",
      "deEmphasized1": "@primitive/neutralPrimitive/neutral4",
      "deEmphasized2": "@primitive/neutralPrimitive/neutral3",
      "deEmphasized3": "@primitive/neutralPrimitive/neutral2",
    },
    "informational": {
      "primary": "@primitive/neutralPrimitive/neutral7",
      "primaryInverse": "@primitive/neutralPrimitive/neutral1",
      "secondary": "@primitive/neutralPrimitive/neutral6",
      "emphasized": "@primitive/neutralPrimitive/neutral8",
      "deEmphasized1": "@primitive/neutralPrimitive/neutral4",
      "deEmphasized2": "@primitive/neutralPrimitive/neutral3",
      "deEmphasized3": "@primitive/neutralPrimitive/neutral2",
    },
    "success": {
      "primary": "@primitive/statusPrimitive/status4",
      "emphasized": "@primitive/statusPrimitive/status5",
      "deEmphasized1": "@primitive/statusPrimitive/status6",
      "deEmphasized2": "@primitive/neutralPrimitive/neutral2",
      "deEmphasized3": "@primitive/neutralPrimitive/neutral3",
    },
    "warning": {
      "primary": "@primitive/statusPrimitive/status10",
      "emphasized": "@primitive/statusPrimitive/status11",
      "deEmphasized1": "@primitive/statusPrimitive/status12",
      "deEmphasized2": "@primitive/neutralPrimitive/neutral3",
      "deEmphasized3": "@primitive/neutralPrimitive/neutral3",
    },
    "error": {
      "primary": "@primitive/statusPrimitive/status1",
      "emphasized": "@primitive/statusPrimitive/status2",
      "deEmphasized1": "@primitive/statusPrimitive/status3",
      "deEmphasized2": "@primitive/neutralPrimitive/neutral2",
      "deEmphasized3": "@primitive/neutralPrimitive/neutral4",
    },
    "positive": {
      "primary": "@primitive/statusPrimitive/status5",
      "emphasized": "@primitive/statusPrimitive/status4",
      "deEmphasized1": "@primitive/statusPrimitive/status6",
      "deEmphasized2": "@primitive/neutralPrimitive/neutral2",
      "deEmphasized3": "@primitive/neutralPrimitive/neutral4",
    },
  },
  "appliedTextAndIcons": {
    "primary": "@semantic/neutral/primary",
    "primaryHeader": "@semantic/neutral/primary",
    "secondary": "@semantic/neutral/secondary",
    "emphasized": "@semantic/neutral/emphasized",
    "deEmphasized": "@semantic/neutral/deEmphasized1",
    "disabled": "@semantic/neutral/deEmphasized1",
    "inversePrimary": "@semantic/neutral/primaryInverse",
    "inverseSecondary": "@semantic/neutral/deEmphasized3",
    "inverseEmphasized": "@semantic/neutral/primaryInverse",
    "inverseDeEmphasized": "@semantic/neutral/deEmphasized2",
    "inverseDisabled": "@semantic/neutral/deEmphasized2",
    "brand": "@semantic/brand/primary",
    "success": "@semantic/brand/primary",
    "successAlt": "@semantic/brand/emphasized",
    "error": "@semantic/error/primary",
    "errorAlt": "@semantic/error/emphasized",
    "accent": "@primitive/brandPrimitive/brand7",
    "accentAlt": "@primitive/brandPrimitive/brand7",
    "warning": "@semantic/warning/primary",
    "warningAlt": "@semantic/warning/emphasized",
    "positive": "@semantic/positive/primary",
    "positiveAlt": "@semantic/positive/emphasized",
  },
  "appliedSurface": {
    "primary": "@semantic/neutral/primaryInverse",
    "primaryHeader": "@semantic/neutral/primaryInverse",
    "secondary": "@semantic/neutral/deEmphasized3",
    "contrast": "@semantic/neutral/emphasized",
    "heavyContrast": "@semantic/neutral/emphasized",
    "inverse": "@semantic/neutral/emphasized",
    "brand": "@semantic/brand/primary",
    "brandSubtitle": "@semantic/brand/deEmphasized1",
    "success": "@semantic/success/deEmphasized1",
    "successSubtitle": "@semantic/success/deEmphasized1",
    "successEmphasized": "@semantic/success/deEmphasized1",
    "warning": "@semantic/warning/deEmphasized1",
    "warningSubtitle": "@semantic/warning/deEmphasized1",
    "warningEmphasized": "@semantic/warning/deEmphasized1",
    "error": "@semantic/error/deEmphasized1",
    "errorSubtitle": "@semantic/error/deEmphasized1",
    "errorEmphasized": "@semantic/error/deEmphasized1",
    "positive": "@semantic/positive/deEmphasized1",
    "positiveSubtitle": "@semantic/positive/deEmphasized1",
    "positiveEmphasized": "@semantic/positive/deEmphasized1",
  },
  "appliedBorder": {
    "primary": "@semantic/neutral/secondary",
    "emphasized": "@semantic/neutral/emphasized",
    "disabled": "@semantic/neutral/deEmphasized1",
    "inversePrimary": "@semantic/neutral/primaryInverse",
    "inverseEmphasized": "@semantic/neutral/emphasized",
    "inverseDisabled": "@semantic/neutral/deEmphasized2",
    "error": "@semantic/error/emphasized",
    "warning": "@semantic/warning/emphasized",
    "success": "@semantic/brand/emphasized",
    "brand": "@semantic/brand/primary",
  },
  "appliedTheme": {
    "buttonPrimary": {
      "default": "@semantic/brand/primary",
      "active": "@semantic/brand/emphasized",
      "disabled": "@semantic/brand/deEmphasized2",
      "hover": "@semantic/brand/primary",
      "tertiary": "@semantic/brand/deEmphasized1",
    },
    "buttonDanger": {
      "default": "@semantic/error/primary",
      "active": "@semantic/error/emphasized",
      "disabled": "@semantic/error/deEmphasized2",
      "hover": "@semantic/error/primary",
      "tertiary": "@semantic/error/deEmphasized1",
    },
    "buttonNeutral": {
      "default": "@semantic/neutral/primary",
      "active": "@semantic/neutral/emphasized",
      "disabled": "@semantic/neutral/deEmphasized1",
      "hover": "@semantic/neutral/primary",
      "tertiary": "@semantic/neutral/deEmphasized3",
    },
    "formControl": {
      "active": "@semantic/brand/primary",
      "inactive": "@appliedSurface/contrast",
      "active-foreground": "@appliedSurface/primary",
      "inactive-foreground": "@appliedSurface/primary",
      "colourBg": "@appliedSurface/brand",
      "fgOnColourBg": "@appliedSurface/primary",
    },
    "formInput": {
      "borderDefault": "@appliedBorder/primary",
      "borderFocused": "@appliedBorder/emphasized",
      "borderDisabled": "@appliedBorder/disabled",
      "borderInverse-default": "@appliedBorder/inversePrimary",
      "borderInverse-focused": "@appliedBorder/inverseEmphasized",
      "borderInverse-disabled": "@appliedBorder/inverseDisabled",
      "textDefault": "@appliedTextAndIcons/primary",
      "textPlaceholder": "@appliedTextAndIcons/deEmphasized",
      "textDisabled": "@appliedTextAndIcons/disabled",
      "inverseTextDefault": "@appliedTextAndIcons/inversePrimary",
      "inverseTextPlaceholder": "@appliedTextAndIcons/inverseDeEmphasized",
      "inverseTextDisabled": "@appliedTextAndIcons/inverseDisabled",
    },
    "navigation": {
      "defaultIcon": "@semantic/neutral/primary",
      "defaultText": "@semantic/neutral/emphasized",
      "activeIcon": "@semantic/brand/primary",
      "activeText": "@semantic/brand/primary",
      "defaultBackground": "@appliedSurface/primary",
      "activeBackground": "@appliedSurface/primary",
    },
    "informationalDefault": {
      "icon": "@appliedTextAndIcons/brand",
      "text": "@appliedTextAndIcons/brand",
      "border": "@appliedBorder/brand",
      "surface": "@appliedSurface/primary",
    },
    "informationalSuccess": {
      "icon": "@appliedTextAndIcons/successAlt",
      "text": "@appliedTextAndIcons/success",
      "border": "@appliedBorder/success",
      "surface": "@appliedSurface/success",
    },
    "informationalWarning": {
      "icon": "@appliedTextAndIcons/warningAlt",
      "text": "@appliedTextAndIcons/warning",
      "border": "@appliedBorder/warning",
      "surface": "@appliedSurface/warning",
    },
    "informationalError": {
      "icon": "@appliedTextAndIcons/errorAlt",
      "text": "@appliedTextAndIcons/error",
      "border": "@appliedBorder/error",
      "surface": "@appliedSurface/error",
    },
    "informationalNeutral": {
      "icon": "@appliedTextAndIcons/secondary",
      "text": "@appliedTextAndIcons/primary",
      "border": "@appliedBorder/primary",
      "surface": "@appliedSurface/primary",
    },
  },
};
