// ignore_for_file: prefer_single_quotes

const sbsaDefaultDesignSystem = {
  "appPrimary": "0xFF0062E1",
  "appOnPrimary": "0xFFFFFFFF",
  "primary": "0xFF0062E1",
  "appSuccess": "0xFF00B877",
  "appOnSuccess": "0xFFFFFFFF",
  "onPrimary": "0xFFFFFFFF",
  "appNeutral": "0xFF3D3D3D",
  "semantic": {
    "brand": {
      "deEmphasized1": "@primitive/neutralPrimitive/neutral2",
      "deEmphasized2": "@primitive/neutralPrimitive/neutral3",
      "deEmphasized3": "@primitive/neutralPrimitive/neutral4",
      "emphasized": "@primitive/brandPrimitive/brand4",
      "primary": "@primitive/brandPrimitive/brand3",
    },
    "error": {
      "deEmphasized1": "@primitive/statusPrimitive/status3",
      "deEmphasized2": "@primitive/neutralPrimitive/neutral2",
      "deEmphasized3": "@primitive/neutralPrimitive/neutral4",
      "emphasized": "@primitive/statusPrimitive/status2",
      "primary": "@primitive/statusPrimitive/status1",
    },
    "informational": {
      "deEmphasized1": "@primitive/neutralPrimitive/neutral4",
      "deEmphasized2": "@primitive/neutralPrimitive/neutral3",
      "deEmphasized3": "@primitive/neutralPrimitive/neutral2",
      "emphasized": "@primitive/neutralPrimitive/neutral8",
      "primary": "@primitive/neutralPrimitive/neutral7",
      "primaryInverse": "@primitive/neutralPrimitive/neutral1",
      "secondary": "@primitive/neutralPrimitive/neutral6",
    },
    "neutral": {
      "deEmphasized1": "@primitive/neutralPrimitive/neutral4",
      "deEmphasized2": "@primitive/neutralPrimitive/neutral3",
      "deEmphasized3": "@primitive/neutralPrimitive/neutral5",
      "emphasized": "@primitive/neutralPrimitive/neutral8",
      "primary": "@primitive/neutralPrimitive/neutral7",
      "primaryInverse": "@primitive/neutralPrimitive/neutral1",
      "secondary": "@primitive/neutralPrimitive/neutral6",
    },
    "positive": {
      "deEmphasized1": "@primitive/statusPrimitive/status6",
      "deEmphasized2": "@primitive/neutralPrimitive/neutral2",
      "deEmphasized3": "@primitive/neutralPrimitive/neutral4",
      "emphasized": "@primitive/statusPrimitive/status4",
      "primary": "@primitive/statusPrimitive/status5",
    },
    "success": {
      "deEmphasized1": "@primitive/statusPrimitive/status6",
      "deEmphasized2": "@primitive/neutralPrimitive/neutral2",
      "deEmphasized3": "@primitive/neutralPrimitive/neutral3",
      "emphasized": "@primitive/statusPrimitive/status5",
      "primary": "@primitive/statusPrimitive/status4",
    },
    "warning": {
      "deEmphasized1": "@primitive/statusPrimitive/status12",
      "deEmphasized2": "@primitive/neutralPrimitive/neutral3",
      "deEmphasized3": "@primitive/neutralPrimitive/neutral3",
      "emphasized": "@primitive/statusPrimitive/status11",
      "primary": "@primitive/statusPrimitive/status10",
    },
  },
  "appError": "0xFFFF4F0C",
  "primitive": {
    "brandPrimitive": {
      "brand1": {"name": "secondary", "value": "0xFF0051FF"},
      "brand2": {"name": "secondary", "value": "0xFF0051FF"},
      "brand3": {
        "name": "primary",
        "usage": "primary, active -tabs, nav text, nav icons, check boxes",
        "value": "0xFF0062E1",
      },
      "brand4": {
        "name": "secondary",
        "usage": "secondary, info success border was 0xFF0051FF",
        "value": "0xFF0033AA",
      },
      "brand5": {"name": "secondary", "value": "0xFF0051FF"},
      "brand6": {"name": "secondary", "value": "0xFF0051FF"},
      "brand7": {"name": "secondary", "value": "0xFF0051FF"},
      "brand8": {"name": "secondary", "value": "0xFF0051FF"},
      "brand9": {"name": "secondary", "value": "0xFF0051FF"},
    },
    "neutralPrimitive": {
      "neutral1": {"name": "white", "value": "0xFFFEFFFF"},
      "neutral2": {
        "name": "SB light grey",
        "uasge": "Icon back ground with outborder was 15 585858 ",
        "value": "0xFFF2F2F2",
      },
      "neutral3": {
        "name": "25",
        "usage": "40 per opacity on #00C2E1 disabled button bg",
        "value": "0xFF97C0F0",
      },
      "neutral4": {
        "name": "medium low emphasized",
        "usage": "search bar label was 50 E3E6EA",
        "value": "0xFF9E9C9F",
      },
      "neutral5": {"name": "pale grey", "value": "0xFFCED3D9"},
      "neutral6": {"name": "light grey", "value": "0xFF565463"},
      "neutral7": {
        "name": "medium grey",
        "usage": "tab bar unselected wants to point to low emphasis BFBFBF",
        "value": "0xFF222E37",
      },
      "neutral8": {"name": "dark grey", "value": "0xFF02070D"},
    },
    "statusPrimitive": {
      "status2": {"name": "error-accent", "value": "0xFFF6C2C2"},
      "status3": {"name": "error-surface", "value": "0xFFDC0A0A"},
      "status4": {"name": "positive-text", "value": "0xFF008545"},
      "status5": {
        "name": "positive-accent",
        "usage": "info surface success was 0xFFBFE0CC",
        "value": "0xFF0033AA",
      },
      "status6": {"name": "positive-surface", "value": "0xFFBFDCFC"},
      "status7": {"name": "info-text", "value": "0xFF00008C"},
      "status8": {"name": "info-accent", "value": "0xFF00008C"},
      "status9": {"name": "info-surface", "value": "0xFF00164E"},
      "status10": {"name": "warning-text", "value": "0xFFFF8000"},
      "status11": {
        "name": "warning-accent",
        "usage": "info border was 0xFFEE9C7",
        "value": "0xFFDC0A0A",
      },
      "status12": {
        "name": "warning-surface",
        "usage": "info surface was 0xFFFFFBF6",
        "value": "0xFFFFEAE4",
      },
      "status1": {"name": "error-text", "value": "0xFFE31E46"},
    },
  },
  "appOnNeutral": "0xFFFFFFFF",
  "appOnError": "0xFFFFFFFF",
  "error": "0xFFDC0A0A",
  "appliedBorder": {
    "emphasized": "@semantic/neutral/emphasized",
    "primary": "@semantic/neutral/secondary",
    "success": "@semantic/brand/emphasized",
    "brand": "@semantic/brand/primary",
    "error": "@semantic/error/emphasized",
    "inverseDisabled": "@semantic/neutral/deEmphasized2",
    "inverseEmphasized": "@semantic/neutral/emphasized",
    "inversePrimary": "@semantic/neutral/primaryInverse",
    "disabled": "@semantic/neutral/deEmphasized1",
    "warning": "@semantic/warning/emphasized",
  },
  "onError": "0xFFFFFFFF",
  "appliedTheme": {
    "informationalWarning": {
      "border": "@appliedBorder/warning",
      "icon": "@appliedTextAndIcons/warningAlt",
      "surface": "@appliedSurface/warning",
      "text": "@appliedTextAndIcons/warning",
    },
    "formInput": {
      "inverseTextDefault": "@appliedTextAndIcons/inversePrimary",
      "borderInverse-disabled": "@appliedBorder/inverseDisabled",
      "textPlaceholder": "@appliedTextAndIcons/deEmphasized",
      "borderDisabled": "@appliedBorder/disabled",
      "textDisabled": "@appliedTextAndIcons/disabled",
      "borderFocused": "@appliedBorder/emphasized",
      "borderInverse-focused": "@appliedBorder/inverseEmphasized",
      "textDefault": "@appliedTextAndIcons/primary",
      "borderDefault": "@appliedBorder/primary",
      "inverseTextPlaceholder": "@appliedTextAndIcons/inverseDeEmphasized",
      "borderInverse-default": "@appliedBorder/inversePrimary",
      "inverseTextDisabled": "@appliedTextAndIcons/inverseDisabled",
    },
    "informationalDefault": {
      "border": "@appliedBorder/brand",
      "icon": "@appliedTextAndIcons/brand",
      "surface": "@appliedSurface/primary",
      "text": "@appliedTextAndIcons/brand",
    },
    "informationalSuccess": {
      "border": "@appliedBorder/success",
      "icon": "@appliedTextAndIcons/successAlt",
      "surface": "@appliedSurface/success",
      "text": "@appliedTextAndIcons/success",
    },
    "buttonPrimary": {
      "active": "@semantic/brand/emphasized",
      "default": "@semantic/brand/primary",
      "disabled": "@semantic/brand/deEmphasized2",
      "hover": "@semantic/brand/primary",
      "tertiary": "@semantic/brand/deEmphasized1",
    },
    "informationalNeutral": {
      "border": "@appliedBorder/primary",
      "icon": "@appliedTextAndIcons/secondary",
      "surface": "@appliedSurface/primary",
      "text": "@appliedTextAndIcons/primary",
    },
    "informationalError": {
      "border": "@appliedBorder/error",
      "icon": "@appliedTextAndIcons/errorAlt",
      "surface": "@appliedSurface/error",
      "text": "@appliedTextAndIcons/error",
    },
    "navigation": {
      "activeBackground": "@appliedSurface/primary",
      "activeIcon": "@semantic/brand/primary",
      "activeText": "@semantic/brand/primary",
      "defaultBackground": "@appliedSurface/primary",
      "defaultIcon": "@semantic/neutral/primary",
      "defaultText": "@semantic/neutral/emphasized",
    },
    "buttonNeutral": {
      "active": "@semantic/neutral/emphasized",
      "default": "@semantic/neutral/primary",
      "disabled": "@semantic/neutral/deEmphasized1",
      "hover": "@semantic/neutral/primary",
      "tertiary": "@semantic/neutral/deEmphasized3",
    },
    "buttonDanger": {
      "active": "@semantic/error/emphasized",
      "default": "@semantic/error/primary",
      "disabled": "@semantic/error/deEmphasized2",
      "hover": "@semantic/error/primary",
      "tertiary": "@semantic/error/deEmphasized1",
    },
    "formControl": {
      "active": "@semantic/brand/primary",
      "active-foreground": "@appliedSurface/primary",
      "colourBg": "@appliedSurface/brand",
      "fgOnColourBg": "@appliedSurface/primary",
      "inactive": "@appliedSurface/contrast",
      "inactive-foreground": "@appliedSurface/primary",
    },
  },
  "onBackground": "0xff606060",
  "appliedTextAndIcons": {
    "errorAlt": "@semantic/error/emphasized",
    "emphasized": "@semantic/neutral/emphasized",
    "primary": "@semantic/neutral/primary",
    "success": "@semantic/brand/primary",
    "deEmphasized": "@semantic/neutral/deEmphasized1",
    "inverseSecondary": "@semantic/neutral/deEmphasized3",
    "successAlt": "@semantic/brand/emphasized",
    "brand": "@semantic/brand/primary",
    "error": "@semantic/error/primary",
    "accent": "@primitive/brandPrimitive/brand7",
    "inverseDisabled": "@semantic/neutral/deEmphasized2",
    "warningAlt": "@semantic/warning/emphasized",
    "primaryHeader": "@semantic/neutral/primaryInverse",
    "positiveAlt": "@semantic/positive/emphasized",
    "inverseEmphasized": "@semantic/neutral/primaryInverse",
    "inversePrimary": "@semantic/neutral/primaryInverse",
    "inverseDeEmphasized": "@semantic/neutral/deEmphasized2",
    "secondary": "@semantic/neutral/secondary",
    "positive": "@semantic/positive/primary",
    "disabled": "@semantic/neutral/deEmphasized1",
    "warning": "@semantic/warning/primary",
    "accentAlt": "@primitive/brandPrimitive/brand7",
  },
  "modal": {"enableIconBackground": false, "enableVerticalActions": true},
  "oldSecondary": "0xFF90a4ae",
  "background": "0xFFFFFFFF",
  "appliedSurface": {
    "errorSubtitle": "@semantic/error/deEmphasized1",
    "primary": "@semantic/neutral/primaryInverse",
    "contrast": "@semantic/neutral/emphasized",
    "success": "@semantic/success/deEmphasized1",
    "successEmphasized": "@semantic/success/deEmphasized1",
    "brand": "@semantic/brand/primary",
    "error": "@semantic/error/deEmphasized1",
    "heavyContrast": "@semantic/neutral/emphasized",
    "errorEmphasized": "@semantic/error/deEmphasized1",
    "primaryHeader": "@semantic/neutral/primaryInverse",
    "inverse": "@primitive/brandPrimitive/brand4",
    "positiveSubtitle": "@semantic/positive/deEmphasized1",
    "secondary": "@semantic/neutral/deEmphasized3",
    "warningSubtitle": "@semantic/warning/deEmphasized1",
    "positive": "@semantic/positive/deEmphasized1",
    "positiveEmphasized": "@semantic/positive/deEmphasized1",
    "successSubtitle": "@semantic/success/deEmphasized1",
    "warning": "@semantic/warning/deEmphasized1",
    "warningEmphasized": "@semantic/warning/deEmphasized1",
    "brandSubtitle": "@semantic/brand/deEmphasized1",
  },
  "onTertiary": "0xFFFFFFFF",
  "tertiary": "0xFF0062E1",
  "appBar": {
    "background": "0xFFFFFFFF",
    "enableSurfaceTint": false,
    "gradientEnd": "0xff0033aa",
    "gradientStart": "0xFF0062E1",
    "useGradient": true,
  },
  "secondary": "0xFF1f1f21",
  "onSecondary": "0xff606060",
  "appWarning": "0xFFFFB848",
  "appOnWarning": "0xFFFFFFFF",
};
